# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven Test Server

on:
  push:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Compile and Build JAR 
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8     
           
    - name: Build with Maven
      run: mvn -B package --file pom.xml 

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }} 
        source: "/home/runner/work/springboot-docker/springboot-docker/target/SpringBootDocker-0.0.1-SNAPSHOT.jar"
        target: "/var/sentora/hostdata/imgglobal/public_html/Olympiad/test"
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }} 
        script: |
          cd /var/sentora/hostdata/imgglobal/public_html/Olympiad/test
          mv /github/workspace/target/SpringBootDocker-0.0.1-SNAPSHOT.jar /
          rm -rf github
          nohup java -jar /SpringBootDocker-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          ls
          echo $(ps -ef | grep 'SpringBootDocker-0.0.1-SNAPSHOT.jar' | grep -v 'grep' | awk '{ printf $2 }')          
